spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ykjykj
    username: root
    url: jdbc:mysql://localhost:3306/Paimon_TravelReservation?useUnicode=true&characterEncoding=utf8&useSSL=false

  security:
    user:
      name: Ayelsh
      password: 962464
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher