spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ykjykj
    url: jdbc:mysql://localhost:3306/Paimon_TravelReservation

#  security:
#    user:
#      name: Ayelsh
#      password: 962464
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher