
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ykjykj
    url: jdbc:mysql://localhost:3306/Paimon_TravelReservation

#  security:
#    user:
#      name: Ayelsh
#      password: 962464
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  mail:
    username: 15768206596@163.com
    password: UHQLMHPWQHLPFEYE
    default-encoding: utf-8
    protocol: smtps
    host: smtp.163.com
    port: 465
    from: 15768206596@163.com
    # 配饰 SSL 加密工厂
    smtp.socketFactoryClass: javax.net.ssl.SSLSocketFactory
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
    debug: true
server:
  port: 80
